use `BetBall`;
SET character_set_client = utf8;
INSERT INTO times (nome, id_time, brasao) VALUES
    ('Bahia', '0' , '../src/assets/team/bahiaIcon.png'), 
    ('Flamengo', '1' , '../src/assets/team/flamengoIcon.png'),
    ('Corinthians', '2', '../src/assets/team/corinthiansIcon.png'),
    ('São Paulo', '3', '../src/assets/team/saoPauloIcon.png'),
    ('Palmeiras', '4', '../src/assets/team/palmeirasIcon.png'),
    ('Internacional', '5', '../src/assets/team/internacionalIcon.png'),
    ('Fluminense', '6', '../src/assets/team/fluminenseIcon.png'),
    ('Athletico-PR', '7', '../src/assets/team/athleticoPR.png'),
    ('Atletico-MG', '8', '../src/assets/team/atleticoMGIcon.png'),
    ('America-MG', '9', '../src/assets/team/americaMGIcon.png'),
    ('Fortaleza', '10', '../src/assets/team/fortalezaIcon.png'),
    ('Botafogo', '11', '../src/assets/team/botafogoIcon.png'),
    ('Santos', '12', '../src/assets/team/santosIcon.png'),
    ('Bragantino', '13' , '../src/assets/team/bragantinoIcon.png'),
    ('Goias', '14' , '../src/assets/team/goiasIcon.png'),
    ('Coritiba', '15', '../src/assets/team/coritibaIcon.png'),
    ('Ceará', '16', '../src/assets/team/cearaIcon.png'),
    ('Cuiabá', '17', '../src/assets/team/cuiabaIcon.png'),
    ('Avai', '18', '../src/assets/team/avaiIcon.png'),
    ('Atletico-GO', '19', '../src/assets/team/atleticoGOIcon.png'),
    ('Juventude', '20', '../src/assets/team/juventudeIcon.png'),
    ('Barcelona', '21', '../src/assets/team/barcelonaIcon.png'), 
    ('Chelsea', '22', '../src/assets/team/chelseaIcon.png'), 
    ('Manchester United','23' , '../src/assets/team/manchesterUnitedIcon.png'),
    ('Milan', '24', '../src/assets/team/milanIcon.png'),
    ('Psg', '25' , '../src/assets/team/psgIcon.png'),
    ('Real Madrid', '26', '../src/assets/team/realMadridIcon.png');